export default [
  "Advice Generator App",
  "Article Preview Component",
  "Base Apparel Coming Soon Page",
  "Blog Preview Card",
  "Equalizer Landing Page",
  "Faq Accordion",
  "Four Card Feature Section",
  "Huddle Landing Page With A Single Introductory Section",
  "Interactive Rating Component",
  "Meeting Landing Page",
  "NFT Preview Card Component",
  "Order Summary Component",
  "Ping Single Column Coming Soon Page",
  "Pod Request Access Landing Page",
  "Product Preview Card Component",
  "Profile Card Component",
  "QR Code Component",
  "Recipe Page",
  "Results Summary Component",
  "Single Price Grid Component",
  "Skilled E-Learning Landing Page",
  "Social Links Profile",
  "Social Profile Section",
  "Stats Preview Card Component",
  "Three Column Preview Card Component",
  "Workit Landing Page",
];
